/**
 * @file installed_components.hpp
 * @brief Definition of InstalledComponents class
 */

#ifndef S2E_SIMULATION_SPACECRAFT_INSTALLED_COMPONENTS_H_
#define S2E_SIMULATION_SPACECRAFT_INSTALLED_COMPONENTS_H_

#include <library/math/Vector.hpp>
#include <interface/log_output/logger.hpp>

/**
 * @class InstalledComponents
 * @brief Base class to express components list installed on a spacecraft
 */
class InstalledComponents {
 public:
  /**
   * @fn ~InstalledComponents
   * @brief Destructor
   */
  virtual ~InstalledComponents() {}

  /**
   * @fn GenerateForce_N_b
   * @brief Return force generated by components in unit Newton in body fixed frame
   * @details Users need to override this function to add force generated by components
   */
  virtual libra::Vector<3> GenerateForce_N_b();

  /**
   * @fn GenerateTorque_Nm_b
   * @brief Return torque generated by components in unit Newton-meter in body fixed frame
   * @details Users need to override this function to add torque generated by components
   */
  virtual libra::Vector<3> GenerateTorque_Nm_b();

  /**
   * @fn LogSetup
   * @brief Setup the logger for components
   * @details Users need to override this function to add logger for components
   */
  virtual void LogSetup(Logger& logger);
};

#endif  // S2E_SIMULATION_SPACECRAFT_INSTALLED_COMPONENTS_H_
