name: validate / renovate.json

on:
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.3.0

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
